### ISSUE TITLE
Rediseñar tarjetas de reservas

### ISSUE THREAD

**Issue by stsewd** [trivialbox/aluc#106]
Las tarjetas actuales contienen información redundante, como el id del usuario. Y como se planea mostrar más información de un laboratorio (mostrar reservas de acuerdo a un laboratorio escogido), el título de la tarjeta también sería redundante.
Qué sugieren poner como nuevo título en cada reserva? La fecha?

**Comment by Krysthyan** [comment]
pero las reservas por parte del admin si debería tener esa información como el id_usuario, en la parte de user estaría bien como titulo la fecha.

**Comment by stsewd** [comment]
Closes on a02e9bcb189ba22cda69bf9035e28fa2aafbfaae
