### ISSUE TITLE
Reservas pasadas de un usuario

### ISSUE THREAD

**Issue by Krysthyan** [trivialbox/aluc#108]
En esa parte cuando el usuario tenga muchas reservas pasadas no creen que estaría de mas esa información... puede que fin de ciclo termine con 80 reservas pasadas, las cuales no le servirían al usuario, mejor seria dejar pasadas solo las del mes.

**Comment by stsewd** [comment]
Si, sólo listas las del último mes estaría bien, y tener una opción de "ver más".
Aunque esta funcionalidad sería mejor implementada sacando de "a poco" desde la base de datos, no todos los resultados de una sola.
Ver sintaxis de LIMIT en mysql.

**Comment by Krysthyan** [comment]
en todo caso si se utliza LIMIT de mysql devolver unas 10 reservas pasadas no mas !!! ordernar por fecha y pasar las pasadas mas actuales

**Comment by stsewd** [comment]
Implementas?

**Comment by Krysthyan** [comment]
no se como separar las pasadas con las nuevas... me toca mover algunas cosas ya que estaba una sola con las nuevas
Pero deja ver como esta la cosa.

**Comment by stsewd** [comment]
Las nuevas son las que tienen el estado de "activa" creo que era.

**Comment by Krysthyan** [comment]
no se como separar las pasadas con las nuevas... me toca mover algunas cosas ya que estaba una sola con las nuevas
Pero deja ver como esta la cosa.
