### ISSUE TITLE
Permitir al administrador/moderador crear reservas para un usuario determinado

### ISSUE THREAD

**Issue by stsewd** [trivialbox/aluc#113]
El administrador y moderador puede crear reservas para un usuario determinado, en este caso se debe guardar en la base de datos el "autor" de la reserva. Si alguien tiene problemas creando la reserva, el moderador o administrador pueda ayudarlo.

**Comment by LaraFranklin** [comment]
Quieren que implemente en la base de datos ahorita esta parte?

**Comment by stsewd** [comment]
@LaraFranklin por ahora creo que no.
