### ISSUE TITLE
Atributos de tabla moderadores

### ISSUE THREAD

**Issue by stsewd** [trivialbox/aluc#18]
Y creo que algo está mal en la tabla moderadores, creo que moderador debería tener un id_laboratorio (sino, significa que el mismo moderador puede ser de varios labs).
Y la tabla moderador_laboratorio desaparece                        
https://github.com/trivialbox/aluc/blob/master/database/DDL.sql#L177                        
a no ser que en esa tabla se guarde otro tipo de información pero lo del id_lab creo que si debe estar en la tabla moderador

**Comment by stsewd** [comment]
@LaraFranklin @Krysthyan

**Comment by LaraFranklin** [comment]
En el principio estuvo asi:
- moderador
  -- id_usuario
  -- id_laboratorio
  para tener como clave a los dos campos pero en el caso de tener mas campos en la normalización se eliminaria id_laboratorio y se crea una nueva tabla. 
  Ahora si creemos necesario poner el horario de trabajo del moderador quedaria como esta ahora.

**Comment by stsewd** [comment]
@LaraFranklin Pero en la tabla moderador sólo el id debería ser clave primaria, y laboratorio queda como un atributo del moderador.
Creo que si horario debería ir en la tabla moderador_laboratorio.
Entonces dónde se deja el atributo de id_laboratorio?

**Comment by stsewd** [comment]
@LaraFranklin No compliquemos mucho, hagamos que el horario sea atributo del laboratorio, de ahí si un moderador le toca de mañana, eso no toquemos.

Yo digo, el atrbuto laboratorio_id queda en la tabla Moderador y la tabla moderador_laboratorio se elimina.

**Comment by stsewd** [comment]
Movido a #21
