### ISSUE TITLE
Validaciones en reservas necesarias 

### ISSUE THREAD

**Issue by LaraFranklin** [trivialbox/aluc#45]
- Excluyente en Clases
 - validar que la hora que ingreso sea cuando el laboratorio este abierto
 - No superar las 2 horas diarias por usuario.

Algo mas que  creen que debe estar validado

**Comment by stsewd** [comment]
> No superar las 2 horas diarias por usuario

- [ ] Tal vez esta restricción no aplicar a profesores.

 - [x] Validar que las reservas se hagan de hasta máximo una semana de antelación?

 - [x] Validar el número de cupos.

**Comment by LaraFranklin** [comment]
Códigos de errores
- [x] 50000 - Clases Excluyente
- [x] 60000 - Error de Horario del laboratorio
- [x] 70000 - Exceso de horass diarias para un usuario
- [x] 80000 - Exceso de la capacidad del laboratorio
- [x] 90000 - Validación del rango de creación de reservas
- [x] 100000 - validación que no se puede ingresar una hora o fecha menor a la actual
- [x] 110000 - Validación para no modificar una reserva que ha sido cancelada
- [x] 120000 - No puede crear dos reservas en el mismo horario
- [x] 130000 - No se ser la fecha de final menos a la de inicio
- [x] 140000 - Vallida que este dentro del tipo de uso (clases, práctica)
- [x] 150000 - Valida que este dentro del tipo se estado (reservado)

**Comment by LaraFranklin** [comment]
Editar Reserva
- [x] 100000 - Validar que la edición se de antes de la hora
-  [x] 50000 - Clases Excluyente
- [x]  60000 - Error de Horario del laboratorio
- [x] 70000 - Exceso de horass diarias para un usuario
- [x] 80000 - Exceso de la capacidad del laboratorio
- [x] 90000 - Validación del rango de creación de reservas

**Comment by stsewd** [comment]
Cierro y agrego la etiqueta #info
