### ISSUE TITLE
numeración de versiones

### ISSUE THREAD

**Issue by stsewd** [trivialbox/aluc#86]
Se debe decidir qué numeración se va a seguir las versiones.
Referirse a <http://semver.org/>

Propongo llevar `X.Y.Z[-tag[.n]]`.
Donde:
X es el número de versión mayor, o sea cuando se hacen cambio muy grandes (posiblemente rompen compatibilidad con versiones anteriores).
Y es el número de versión menor, o sea cuando se agregan nuevas cosas, pero, se mantiene la compatibilidad con versiones anteriores.
Z es el número de parche, es decir, cuando se arreglan bugs o alguna cosa muy pequeña. Y
-tag, que sólo se usará para indicar si una versión está en alpha o en beta (depende de que tan madura esté la versión). Y adicionalmente se puede agregar un número -tag.3

Con esto ahora mismo, creo que estaríamos en la versión 0.1.0-alpha.2,  y la alpha.1 sería cuando se presentó le proyecto? o partimos desde la alpha.1, o sea sólo 0.1.0-alpha?

**Comment by Krysthyan** [comment]
me parece interesante pero desarrolle el tema !!!... creo que sería 0.1.0-alpha.2, ya cuenta lo que presentamos

**Comment by stsewd** [comment]
@Krysthyan desarrollar más cómo?
Cómo haríamos luego?
Si es así, se crearía tags con git, y nos manejaríamos con otra rama aparte de la master donde estaría la "versión estable". La master quedaría designada a tener lo último de lo último.
Incluso github permite "comentar" cada versión (release) especificando qué se agregó/quitó/resolvió.

Ejemplo: https://github.com/atom/atom/releases

**Comment by stsewd** [comment]
Bueno, ya quedó. Cuando el proyecto alcance una mayor madurez, se creará la otra rama para trabajar ahí.
Primer release: https://github.com/trivialbox/aluc/releases/tag/v0.1.0-alpha
