### ISSUE TITLE
Tipos de reportes

### ISSUE THREAD

**Issue by Krysthyan** [trivialbox/aluc#94]
# **getInstance**
- Reporte de un año en concreto de todas las reservas que pertenezcan a ese año. -> `getInstance(2016)`
- Reporte de un año en un usuario en concreto. -> `getInstance(2016, 11033839393)`

# **getReporteDia**
- Reporte de todas las reservas de un dia de todos los usuarios.  -> `getReporteDia(2016-11-1)`
- Reporte de un dia un usuario en concreto -> `getReporteDia(2016-11-1, 11037383833)`
- Reporte de un dia de un usuario y laboratorio en concreto -> `getReporteDia(2016-11-1, 11037383833, 11)`
- Reporte de un dia de un laboratorio en concreto -> `getReporteDia(2016-11-1, null, 11)`

# **getReporteSemana**
- Reporte de una semana de todas las reservas de un año en concreto -> `getReporteSemana(40,2016)`
- Reporte de una semana, de un año y usuario en concreto -> `getReporteSemana(40,2016,1110838383)`
- Reporte de una semana, de un año, usuario y laboratorio en concreto ->`getReporteSemana(40,2016, 1108939393, 11)`
- Reporte de una semana, de un año y un laboratorio en concreto -> `getReporteSemana(40, 2016, null, 11)`

# **getReporteMes**
- Reporte de un mes de todas las reservas de un año en concreto -> `getReporteMes(12, 2016)`
- Reporte de un mes, de un año y usuario en concreto -> `getReporteMes(12, 2016, 1110838383)`
- Reporte de un mes, de un año, usuario y laboratorio en concreto ->`getReporteMes(12, 2016, 1108939393, 11)`
- Reporte de un mes, de un año y un laboratorio en concreto -> `getReporteMes(12, 2016, null, 11)`

**Comment by stsewd** [comment]
Creo que quedaron claros los tipos de reportes. Cierro este issue.
Nota: Los métodos listados arriba, actualmente no necesitan el parámetro de "fecha", ya que obtiene la fecha actual. Adicionalmente se tiene un método para obtener reportes en un rango de fechas.
